### PR TITLE
Updated location of storage.json file causing the error

### PR DESCRIPTION
**Pull request by gabey14**

### CODE REVIEW

**Review by KorigamiK — COMMENTED** [review]
You should respect the tab size of the codespace for this project but other than that LGTM.

**Comment by gabey14** [comment]
I have updated the file which was formatted by mistake.

**Comment by SIMULATAN** [comment]
Just as a note to people seeing this; I forked the repo and changed the branch name to "main" so you can install the fixed version using [this](https://github.com/SIMULATAN/ulauncher-vscode-recent) URL.

Thanks a lot for the fix Abey :heart:

**Comment by andresatierf** [comment]
@plibither8 merge pls?

**Comment by plibither8** [comment]
@gabey14 @SIMULATAN @andresatierf thank you so so much for the patience. I have been busy elsewhere, and haven't been actively using my Linux machine, unfortunately. Merging this right away!

PS: You can also contact @mattalexx, he too is maintaining this repo :)

**Comment by andresatierf** [comment]
@plibither8 thank you very much

**Pull request merged**
